"""Build and validate the isolated Python runtime used by SWE-agent tools.

The SWE-bench images intentionally activate their per-repository ``testbed``
Conda environment.  That environment is part of the workload being measured;
it must not be changed merely to make an agent-side tool importable.  The
reviewed tool bundles therefore get a separate, explicitly named Python
environment inside the container.  This module builds the small bundle overlay
that SWE-agent uploads and records every source/generated byte in a manifest.

The builder is deliberately limited to the three bundles used by the reviewed
configuration.  It does not discover arbitrary files, edit the pinned
SWE-agent checkout, or add a fallback to the image's ``python`` command.
"""

from __future__ import annotations

import ast
import hashlib
import json
import os
import re
import shlex
import stat
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping


TOOL_RUNTIME_SCHEMA = "assignment.tool-runtime.v1"
TOOL_RUNTIME_CONFIG_SCHEMA = "assignment.tool-runtime-config.v1"
TOOL_RUNTIME_MANIFEST_NAME = "tool_runtime_manifest.json"
TOOL_RUNTIME_CONFIG_NAME = "tool_runtime_config.json"
TOOL_BUNDLE_NAMES = ("registry", "edit_anthropic", "review_on_submit_m")
DEFAULT_REMOTE_TOOLS_ROOT = "/root/tools"
DEFAULT_REMOTE_VENV = "/root/tools/.agentic_tool_python"
DEFAULT_BOOTSTRAP_PYTHON = "/opt/miniconda3/bin/python3.11"
DEFAULT_UPSTREAM_CONFIG_PATHS = ("config/default.yaml",)

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_REQUIREMENT_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9_.-]*)(?:\[[A-Za-z0-9_,.-]+\])?==(?P<version>[^\s;#]+)$"
)
_PYTHON_SHEBANG_RE = re.compile(r"^#!.*\bpython(?:3(?:\.[0-9]+)?)?(?:\s|$)")


class ToolRuntimeError(ValueError):
    """The tool-runtime source, manifest, or artifact is not safe to use."""


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    try:
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
    except OSError as exc:
        raise ToolRuntimeError(f"cannot hash {path}: {exc}") from exc
    return digest.hexdigest()


def _git_output(source_root: Path, *arguments: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(source_root), *arguments],
            capture_output=True,
            check=False,
            text=True,
        )
    except OSError as exc:
        raise ToolRuntimeError(f"cannot inspect pinned SWE-agent git source: {exc}") from exc
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        raise ToolRuntimeError(
            f"pinned SWE-agent git command failed ({' '.join(arguments)}): {detail}"
        )
    return result.stdout.strip()


def _git_blob_for_source(source_root: Path, revision: str, source_path: Path) -> str:
    relative = _relative_posix(source_path, source_root, "source file")
    expected = _git_output(source_root, "rev-parse", f"{revision}:{relative}")
    actual = _git_output(source_root, "hash-object", "--", str(source_path))
    if not re.fullmatch(r"[0-9a-f]{40}", expected) or actual != expected:
        raise ToolRuntimeError(
            f"source bytes drift from pinned SWE-agent git blob: {relative}"
        )
    return expected


def _regular_file(path: Path, label: str) -> None:
    if path.is_symlink() or not path.is_file():
        raise ToolRuntimeError(f"{label} must be a regular file: {path}")


def _directory(path: Path, label: str) -> None:
    if path.is_symlink() or not path.is_dir():
        raise ToolRuntimeError(f"{label} must be a regular directory: {path}")


def _normalise_package_name(requirement: str) -> str:
    match = _REQUIREMENT_RE.fullmatch(requirement)
    if match is None:
        raise ToolRuntimeError(
            "tool wheel requirements must be exact, hashable == pins without "
            f"markers or URLs: {requirement!r}"
        )
    return re.sub(r"[-_.]+", "-", match.group("name")).lower()


def _relative_posix(path: Path, root: Path, label: str) -> str:
    try:
        relative = path.relative_to(root)
    except ValueError as exc:
        raise ToolRuntimeError(f"{label} is outside its declared root: {path}") from exc
    if relative.is_absolute() or ".." in relative.parts:
        raise ToolRuntimeError(f"{label} has unsafe relative path: {relative}")
    return relative.as_posix()


def _validate_remote_path(value: str, label: str) -> None:
    if not isinstance(value, str) or not value.startswith("/"):
        raise ToolRuntimeError(f"{label} must be an absolute POSIX path")
    path = Path(value)
    if ".." in path.parts:
        raise ToolRuntimeError(f"{label} must not contain '..': {value}")


@dataclass(frozen=True)
class WheelPin:
    """One exact wheel and requirement line in the offline tool archive."""

    requirement: str
    filename: str
    sha256: str

    def __post_init__(self) -> None:
        package = _normalise_package_name(self.requirement)
        del package  # validation is the purpose of the call
        if (
            not isinstance(self.filename, str)
            or not self.filename.endswith(".whl")
            or Path(self.filename).name != self.filename
            or not self.filename
        ):
            raise ToolRuntimeError(f"wheel filename must be a flat .whl name: {self.filename!r}")
        if not _SHA256_RE.fullmatch(self.sha256):
            raise ToolRuntimeError(f"wheel SHA-256 is not canonical: {self.sha256!r}")


@dataclass(frozen=True)
class ToolRuntimeSpec:
    """Inputs needed to make one immutable tool-bundle overlay."""

    source_root: Path
    output_root: Path
    wheelhouse: Path
    wheel_pins: tuple[WheelPin, ...]
    upstream_revision: str
    bootstrap_python: str = DEFAULT_BOOTSTRAP_PYTHON
    remote_tools_root: str = DEFAULT_REMOTE_TOOLS_ROOT
    remote_venv: str = DEFAULT_REMOTE_VENV
    bundle_names: tuple[str, ...] = TOOL_BUNDLE_NAMES
    upstream_config_paths: tuple[str, ...] = DEFAULT_UPSTREAM_CONFIG_PATHS

    def __post_init__(self) -> None:
        if not isinstance(self.upstream_revision, str) or not self.upstream_revision.strip():
            raise ToolRuntimeError("the pinned SWE-agent upstream revision is required")
        if not re.fullmatch(r"[0-9a-f]{40}", self.upstream_revision):
            raise ToolRuntimeError(
                "the pinned SWE-agent upstream revision must be a 40-character SHA-1"
            )
        _validate_remote_path(self.bootstrap_python, "bootstrap_python")
        _validate_remote_path(self.remote_tools_root, "remote_tools_root")
        _validate_remote_path(self.remote_venv, "remote_venv")
        if self.bundle_names != TOOL_BUNDLE_NAMES:
            raise ToolRuntimeError(
                "tool runtime is intentionally bounded to registry, edit_anthropic, "
                "and review_on_submit_m"
            )
        if not self.upstream_config_paths:
            raise ToolRuntimeError("at least one pinned upstream config path is required")
        config_paths: set[str] = set()
        for relative in self.upstream_config_paths:
            path = Path(relative) if isinstance(relative, str) else None
            if (
                path is None
                or not relative
                or path.is_absolute()
                or ".." in path.parts
                or path.as_posix() != relative
            ):
                raise ToolRuntimeError(
                    f"upstream config path must be a safe relative POSIX path: {relative!r}"
                )
            if relative in config_paths:
                raise ToolRuntimeError(f"duplicate upstream config path: {relative}")
            config_paths.add(relative)
        if not self.wheel_pins:
            raise ToolRuntimeError("the offline tool wheel set is empty")
        names: set[str] = set()
        filenames: set[str] = set()
        for pin in self.wheel_pins:
            package = _normalise_package_name(pin.requirement)
            if package in names:
                raise ToolRuntimeError(f"duplicate wheel requirement: {package}")
            if pin.filename in filenames:
                raise ToolRuntimeError(f"duplicate wheel filename: {pin.filename}")
            names.add(package)
            filenames.add(pin.filename)


@dataclass(frozen=True)
class ToolRuntimeBuild:
    """Paths and hashes returned by :func:`build_tool_runtime`."""

    root: Path
    manifest_path: Path
    config_path: Path
    bundle_paths: tuple[Path, ...]
    manifest_sha256: str
    config_sha256: str

    def sweagent_bundles(self) -> list[dict[str, Any]]:
        """Return the local bundle records expected by SWE-agent's config."""

        return [
            {"path": str(path), "hidden_tools": []}
            for path in self.bundle_paths
        ]


def materialize_sweagent_config(
    base_config: Mapping[str, Any],
    build: ToolRuntimeBuild,
    output_path: Path,
) -> Path:
    """Write the actual SWE-agent config with the built bundle paths.

    The runtime metadata config emitted by :func:`build_tool_runtime` is an
    assignment provenance record, not a SWE-agent config.  This helper keeps
    those concerns separate: it preserves every existing config field and
    changes only ``agent.tools.bundles`` to the exact mirrored local paths.
    The caller should hash and bind this generated config in its runner
    manifest.
    """

    if not isinstance(base_config, Mapping):
        raise ToolRuntimeError("SWE-agent base config must be a mapping")
    try:
        config = json.loads(json.dumps(base_config))
    except (TypeError, ValueError) as exc:
        raise ToolRuntimeError(f"SWE-agent base config is not JSON-serializable: {exc}") from exc
    agent = config.get("agent")
    if not isinstance(agent, dict):
        raise ToolRuntimeError("SWE-agent base config lacks an agent mapping")
    tools = agent.get("tools")
    if not isinstance(tools, dict):
        raise ToolRuntimeError("SWE-agent base config lacks agent.tools")
    tools["bundles"] = build.sweagent_bundles()
    output_path = output_path.expanduser().resolve()
    if output_path.exists() or output_path.is_symlink():
        raise ToolRuntimeError(f"SWE-agent config output already exists: {output_path}")
    if output_path.parent.is_symlink() or not output_path.parent.is_dir():
        raise ToolRuntimeError(
            f"SWE-agent config output parent is unavailable: {output_path.parent}"
        )
    _write_bytes(output_path, _json_bytes(config), 0o644)
    return output_path


def _json_bytes(value: Mapping[str, Any]) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


def _write_bytes(path: Path, data: bytes, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    os.chmod(path, mode)


def _generated_install_script(spec: ToolRuntimeSpec) -> bytes:
    bootstrap = shlex.quote(spec.bootstrap_python)
    remote_venv = shlex.quote(spec.remote_venv)
    return (
        "#!/usr/bin/env bash\n"
        "(\n"
        "  set -euo pipefail\n"
        "  bundle_dir=$(cd -- \"$(dirname -- \"${BASH_SOURCE[0]}\")\" && pwd)\n"
        f"  bootstrap_python={bootstrap}\n"
        f"  tool_venv={remote_venv}\n"
        "  wheelhouse=\"$bundle_dir/wheelhouse\"\n"
        "  requirements=\"$bundle_dir/requirements.lock\"\n"
        "\n"
        "  if [[ ! -x \"$bootstrap_python\" ]]; then\n"
        "    echo \"agentic tool bootstrap interpreter is unavailable: $bootstrap_python\" >&2\n"
        "    exit 127\n"
        "  fi\n"
        "  \"$bootstrap_python\" -c 'import sys; raise SystemExit("
        "\"tool bootstrap requires Python >= 3.8\" if sys.version_info < (3, 8) else 0)' \\\n"
        "    || { rc=$?; echo \"agentic tool bootstrap version check failed\" >&2; "
        "exit \"$rc\"; }\n"
        "  if [[ ! -x \"$tool_venv/bin/python\" ]]; then\n"
        "    \"$bootstrap_python\" -m venv \"$tool_venv\" \\\n"
        "      || { rc=$?; echo \"agentic tool virtualenv creation failed\" >&2; exit \"$rc\"; }\n"
        "  fi\n"
        "  if [[ ! -x \"$tool_venv/bin/python\" ]]; then\n"
        "    echo \"agentic tool virtualenv was not created: $tool_venv\" >&2\n"
        "    exit 127\n"
        "  fi\n"
        "  \"$tool_venv/bin/python\" -c 'import sys; raise SystemExit("
        "\"tool venv is not Python >= 3.8\" if sys.version_info < (3, 8) else 0)' \\\n"
        "    || { rc=$?; echo \"agentic tool venv version check failed\" >&2; exit \"$rc\"; }\n"
        "  \"$tool_venv/bin/python\" -m pip install \\\n"
        "    --disable-pip-version-check --no-cache-dir --no-index \\\n"
        "    --find-links \"$wheelhouse\" --require-hashes -r \"$requirements\" \\\n"
        "    || { rc=$?; echo \"agentic tool wheel installation failed\" >&2; exit \"$rc\"; }\n"
        "  \"$tool_venv/bin/python\" - <<'PY' || { rc=$?; "
        "echo \"agentic tool import check failed\" >&2; exit \"$rc\"; }\n"
        "import tree_sitter  # noqa: F401\n"
        "import tree_sitter_languages  # noqa: F401\n"
        "PY\n"
        ")\n"
    ).encode("utf-8")


def _patch_python_shebang(data: bytes, remote_venv: str) -> tuple[bytes, str | None]:
    first, separator, remainder = data.partition(b"\n")
    try:
        first_text = first.decode("utf-8")
    except UnicodeDecodeError:
        return data, None
    if not separator or not _PYTHON_SHEBANG_RE.match(first_text):
        return data, None
    replacement = f"#!{remote_venv}/bin/python".encode("utf-8") + separator + remainder
    return replacement, "python_entrypoint_shebang"


def _copy_bundle(
    *,
    source_bundle: Path,
    output_bundle: Path,
    bundle_name: str,
    spec: ToolRuntimeSpec,
    rows: list[dict[str, Any]],
) -> None:
    _directory(source_bundle, f"source bundle {bundle_name}")
    for current, directories, filenames in os.walk(source_bundle, topdown=True, followlinks=False):
        current_path = Path(current)
        directories.sort()
        filenames.sort()
        for directory in directories:
            candidate = current_path / directory
            if candidate.is_symlink():
                raise ToolRuntimeError(f"source bundle contains a symlink: {candidate}")
        for filename in filenames:
            source_path = current_path / filename
            _regular_file(source_path, f"source bundle file {bundle_name}")
            relative = source_path.relative_to(source_bundle)
            output_path = output_bundle / relative
            source_data = source_path.read_bytes()
            source_git_blob_sha1 = _git_blob_for_source(
                spec.source_root, spec.upstream_revision, source_path
            )
            archive_path = (
                spec.output_root
                / "upstream_source"
                / source_path.relative_to(spec.source_root)
            )
            _append_generated_row(
                path=archive_path,
                output_root=spec.output_root,
                data=source_data,
                mode=stat.S_IMODE(source_path.stat().st_mode),
                transformation="upstream_source_archive",
                rows=rows,
                source_path=_relative_posix(
                    source_path, spec.source_root, "source archive path"
                ),
                source_sha256=_sha256_bytes(source_data),
                source_git_blob_sha1=source_git_blob_sha1,
            )
            output_data = source_data
            transformation = "unchanged"
            if bundle_name == "edit_anthropic" and relative == Path("install.sh"):
                output_data = _generated_install_script(spec)
                transformation = "offline_tool_venv_install"
            elif relative.parts and relative.parts[0] == "bin":
                output_data, shebang_transformation = _patch_python_shebang(
                    source_data, spec.remote_venv
                )
                if shebang_transformation is not None:
                    transformation = shebang_transformation
            _write_bytes(output_path, output_data, stat.S_IMODE(source_path.stat().st_mode))
            rows.append(
                {
                    "path": _relative_posix(output_path, spec.output_root, "generated bundle path"),
                    "source_path": _relative_posix(
                        source_path, spec.source_root, "source bundle path"
                    ),
                    "source_sha256": _sha256_bytes(source_data),
                    "source_git_blob_sha1": source_git_blob_sha1,
                    "output_sha256": _sha256_bytes(output_data),
                    "mode": stat.S_IMODE(source_path.stat().st_mode),
                    "transformation": transformation,
                }
            )


def _append_generated_row(
    *,
    path: Path,
    output_root: Path,
    data: bytes,
    mode: int,
    transformation: str,
    rows: list[dict[str, Any]],
    source_path: str | None = None,
    source_sha256: str | None = None,
    source_git_blob_sha1: str | None = None,
) -> None:
    _write_bytes(path, data, mode)
    rows.append(
        {
            "path": _relative_posix(path, output_root, "generated file path"),
            "source_path": source_path,
            "source_sha256": source_sha256,
            "source_git_blob_sha1": source_git_blob_sha1,
            "output_sha256": _sha256_bytes(data),
            "mode": mode,
            "transformation": transformation,
        }
    )


def _validate_wheelhouse(spec: ToolRuntimeSpec) -> dict[str, Path]:
    _directory(spec.wheelhouse, "offline wheelhouse")
    expected = {pin.filename for pin in spec.wheel_pins}
    actual: set[str] = set()
    for current, directories, filenames in os.walk(
        spec.wheelhouse, topdown=True, followlinks=False
    ):
        current_path = Path(current)
        for directory in directories:
            candidate = current_path / directory
            if candidate.is_symlink():
                raise ToolRuntimeError(f"offline wheelhouse contains a symlink: {candidate}")
            raise ToolRuntimeError(
                "offline wheelhouse must be a flat directory of exactly pinned wheels"
            )
        for filename in filenames:
            path = current_path / filename
            _regular_file(path, "offline wheelhouse entry")
            if path.parent != spec.wheelhouse:
                raise ToolRuntimeError("offline wheelhouse must be a flat directory")
            actual.add(filename)
    if actual != expected:
        raise ToolRuntimeError(
            "offline wheelhouse files do not match pinned set; "
            f"missing={sorted(expected - actual)}, "
            f"unexpected={sorted(actual - expected)}"
        )
    paths: dict[str, Path] = {}
    for pin in spec.wheel_pins:
        path = spec.wheelhouse / pin.filename
        actual_sha = _sha256_file(path)
        if actual_sha != pin.sha256:
            raise ToolRuntimeError(f"wheel hash mismatch for {pin.filename}")
        paths[pin.filename] = path
    return paths


def _requirements_lock(spec: ToolRuntimeSpec) -> bytes:
    return "".join(
        f"{pin.requirement} --hash=sha256:{pin.sha256}\n" for pin in spec.wheel_pins
    ).encode("utf-8")


def _archive_upstream_configs(
    *,
    spec: ToolRuntimeSpec,
    rows: list[dict[str, Any]],
) -> None:
    """Archive the exact pinned config bytes alongside transformed bundles."""

    for relative in spec.upstream_config_paths:
        source_path = spec.source_root / relative
        _regular_file(source_path, f"pinned upstream config {relative}")
        source_data = source_path.read_bytes()
        source_git_blob_sha1 = _git_blob_for_source(
            spec.source_root, spec.upstream_revision, source_path
        )
        archive_path = spec.output_root / "upstream_source" / relative
        _append_generated_row(
            path=archive_path,
            output_root=spec.output_root,
            data=source_data,
            mode=stat.S_IMODE(source_path.stat().st_mode),
            transformation="upstream_config_archive",
            rows=rows,
            source_path=relative,
            source_sha256=_sha256_bytes(source_data),
            source_git_blob_sha1=source_git_blob_sha1,
        )


def build_tool_runtime(spec: ToolRuntimeSpec) -> ToolRuntimeBuild:
    """Mirror the pinned tool bundles and generate an offline runtime overlay.

    ``spec.output_root`` must not exist.  This prevents a later case from
    silently reusing a partially built or previously modified bundle.  The
    resulting config uses paths relative to its own directory; callers may
    copy the complete directory into case-local execution inputs and resolve
    those paths there.
    """

    source_root = spec.source_root.expanduser().resolve()
    output_root = spec.output_root.expanduser().resolve()
    wheelhouse = spec.wheelhouse.expanduser().resolve()
    _directory(source_root, "pinned SWE-agent source root")
    actual_revision = _git_output(source_root, "rev-parse", "--verify", "HEAD")
    if actual_revision != spec.upstream_revision:
        raise ToolRuntimeError(
            "pinned SWE-agent source HEAD does not match the requested upstream revision: "
            f"{actual_revision} != {spec.upstream_revision}"
        )
    if output_root.exists() or output_root.is_symlink():
        raise ToolRuntimeError(f"tool-runtime output already exists: {output_root}")
    if output_root.parent.is_symlink() or not output_root.parent.is_dir():
        raise ToolRuntimeError(f"tool-runtime output parent is unavailable: {output_root.parent}")
    wheel_paths = _validate_wheelhouse(
        ToolRuntimeSpec(
            source_root=source_root,
            output_root=output_root,
            wheelhouse=wheelhouse,
            wheel_pins=spec.wheel_pins,
            upstream_revision=spec.upstream_revision,
            bootstrap_python=spec.bootstrap_python,
            remote_tools_root=spec.remote_tools_root,
            remote_venv=spec.remote_venv,
            bundle_names=spec.bundle_names,
            upstream_config_paths=spec.upstream_config_paths,
        )
    )
    output_root.mkdir(parents=True, exist_ok=False)
    rows: list[dict[str, Any]] = []
    _archive_upstream_configs(spec=spec, rows=rows)
    bundle_paths: list[Path] = []
    for bundle_name in spec.bundle_names:
        source_bundle = source_root / "tools" / bundle_name
        output_bundle = output_root / "bundles" / bundle_name
        _copy_bundle(
            source_bundle=source_bundle,
            output_bundle=output_bundle,
            bundle_name=bundle_name,
            spec=spec,
            rows=rows,
        )
        bundle_paths.append(output_bundle)

    edit_bundle = output_root / "bundles" / "edit_anthropic"
    requirements_data = _requirements_lock(spec)
    requirements_path = edit_bundle / "requirements.lock"
    if requirements_path.exists():
        raise ToolRuntimeError(
            f"source bundle already contains generated path: {requirements_path}"
        )
    _append_generated_row(
        path=requirements_path,
        output_root=output_root,
        data=requirements_data,
        mode=0o644,
        transformation="offline_requirements_lock",
        rows=rows,
    )
    wheel_output_dir = edit_bundle / "wheelhouse"
    wheel_output_dir.mkdir(parents=True, exist_ok=False)
    wheel_rows: list[dict[str, Any]] = []
    for pin in spec.wheel_pins:
        source_path = wheel_paths[pin.filename]
        output_path = wheel_output_dir / pin.filename
        data = source_path.read_bytes()
        _append_generated_row(
            path=output_path,
            output_root=output_root,
            data=data,
            mode=0o644,
            transformation="offline_pinned_wheel_copy",
            rows=rows,
            source_path=f"input/wheelhouse/{pin.filename}",
            source_sha256=pin.sha256,
        )
        wheel_rows.append(
            {
                "filename": pin.filename,
                "requirement": pin.requirement,
                "sha256": pin.sha256,
                "path": _relative_posix(output_path, output_root, "wheel output path"),
            }
        )

    config = {
        "schema_version": TOOL_RUNTIME_CONFIG_SCHEMA,
        "upstream_revision": spec.upstream_revision,
        "manifest_path": TOOL_RUNTIME_MANIFEST_NAME,
        "bootstrap_python": spec.bootstrap_python,
        "remote_tools_root": spec.remote_tools_root,
        "remote_venv": spec.remote_venv,
        "bundles": [
            {
                "name": bundle_name,
                "path": f"bundles/{bundle_name}",
                "remote_path": f"{spec.remote_tools_root}/{bundle_name}",
                "hidden_tools": [],
            }
            for bundle_name in spec.bundle_names
        ],
        "offline_dependencies": {
            "bundle": "edit_anthropic",
            "requirements_path": "bundles/edit_anthropic/requirements.lock",
            "wheelhouse_path": "bundles/edit_anthropic/wheelhouse",
            "wheels": wheel_rows,
        },
        "no_task_path_change": True,
    }
    config_path = output_root / TOOL_RUNTIME_CONFIG_NAME
    config_data = _json_bytes(config)
    _append_generated_row(
        path=config_path,
        output_root=output_root,
        data=config_data,
        mode=0o644,
        transformation="generated_runtime_config",
        rows=rows,
    )

    rows.sort(key=lambda row: row["path"])
    manifest = {
        "schema_version": TOOL_RUNTIME_SCHEMA,
        "upstream_repository": "SWE-agent",
        "upstream_revision": spec.upstream_revision,
        "upstream_source_root": str(source_root),
        "source_bundle_paths": [f"tools/{name}" for name in spec.bundle_names],
        "source_config_paths": list(spec.upstream_config_paths),
        "runtime": {
            "bootstrap_python": spec.bootstrap_python,
            "remote_tools_root": spec.remote_tools_root,
            "remote_venv": spec.remote_venv,
            "python_entrypoint_shebang": f"#!{spec.remote_venv}/bin/python",
            "no_task_path_change": True,
        },
        "transformations": {
            "unchanged": "source bytes copied exactly",
            "python_entrypoint_shebang": (
                f"replace only the first shebang with #!{spec.remote_venv}/bin/python"
            ),
            "offline_tool_venv_install": (
                "edit_anthropic install uses only the generated hash-locked wheelhouse"
            ),
        },
        "metadata_config_path": TOOL_RUNTIME_CONFIG_NAME,
        "source_archive_root": "upstream_source",
        "bundles": list(spec.bundle_names),
        "offline_wheels": wheel_rows,
        "files": rows,
        "file_count": len(rows),
        "manifest_excluded_from_file_list": True,
    }
    manifest_path = output_root / TOOL_RUNTIME_MANIFEST_NAME
    _write_bytes(manifest_path, _json_bytes(manifest), 0o644)
    return ToolRuntimeBuild(
        root=output_root,
        manifest_path=manifest_path,
        config_path=config_path,
        bundle_paths=tuple(bundle_paths),
        manifest_sha256=_sha256_file(manifest_path),
        config_sha256=_sha256_file(config_path),
    )


def _read_json(path: Path, label: str) -> dict[str, Any]:
    _regular_file(path, label)
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ToolRuntimeError(f"cannot read {label}: {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ToolRuntimeError(f"{label} must be a JSON object: {path}")
    return value


def _read_sweagent_config(path: Path) -> dict[str, Any]:
    """Read JSON or the pinned config's YAML-wrapped JSON string."""

    _regular_file(path, "SWE-agent config")
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise ToolRuntimeError(f"cannot read SWE-agent config: {path}: {exc}") from exc
    try:
        value: Any = json.loads(text)
    except json.JSONDecodeError:
        try:
            value = ast.literal_eval(text)
        except (SyntaxError, ValueError) as exc:
            raise ToolRuntimeError(
                f"SWE-agent config is not JSON or a wrapped JSON string: {path}"
            ) from exc
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except json.JSONDecodeError as exc:
            raise ToolRuntimeError(
                f"YAML-wrapped SWE-agent config contains invalid JSON: {path}"
            ) from exc
    if not isinstance(value, dict):
        raise ToolRuntimeError(f"SWE-agent config must decode to a JSON object: {path}")
    return value


def _validate_sweagent_config(
    config_path: Path,
    root: Path,
    expected_revision: str,
) -> dict[str, Any]:
    config = _read_sweagent_config(config_path)
    agent = config.get("agent")
    if not isinstance(agent, dict):
        raise ToolRuntimeError("SWE-agent config lacks agent mapping")
    tools = agent.get("tools")
    if not isinstance(tools, dict):
        raise ToolRuntimeError("SWE-agent config lacks agent.tools mapping")
    bundles = tools.get("bundles")
    if not isinstance(bundles, list) or len(bundles) != len(TOOL_BUNDLE_NAMES):
        raise ToolRuntimeError("SWE-agent config does not bind exactly the reviewed tool bundles")
    resolved_paths: list[str] = []
    for bundle_name, row in zip(TOOL_BUNDLE_NAMES, bundles):
        if not isinstance(row, dict) or not isinstance(row.get("path"), str):
            raise ToolRuntimeError("SWE-agent config contains an invalid tool bundle row")
        claimed = Path(row["path"])
        if not claimed.is_absolute():
            claimed = config_path.parent / claimed
        claimed = claimed.expanduser().resolve()
        expected = (root / "bundles" / bundle_name).resolve()
        if claimed != expected:
            raise ToolRuntimeError(
                f"SWE-agent config bundle path does not bind {bundle_name}: {claimed} != {expected}"
            )
        _directory(claimed, "SWE-agent configured tool bundle")
        resolved_paths.append(str(claimed))
    return {
        "path": str(config_path),
        "sha256": _sha256_file(config_path),
        "upstream_revision": expected_revision,
        "bundle_paths": resolved_paths,
    }


def _actual_regular_files(root: Path) -> set[str]:
    actual: set[str] = set()
    for current, directories, filenames in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        for directory in directories:
            candidate = current_path / directory
            if candidate.is_symlink():
                raise ToolRuntimeError(f"runtime bundle contains a symlink: {candidate}")
        for filename in filenames:
            candidate = current_path / filename
            _regular_file(candidate, "runtime bundle file")
            actual.add(_relative_posix(candidate, root, "runtime bundle file"))
    return actual


def _check_manifest_rows(manifest: Mapping[str, Any], root: Path) -> dict[str, dict[str, Any]]:
    rows = manifest.get("files")
    if not isinstance(rows, list) or not rows:
        raise ToolRuntimeError("tool runtime manifest has no file rows")
    indexed: dict[str, dict[str, Any]] = {}
    for row in rows:
        if not isinstance(row, dict):
            raise ToolRuntimeError("tool runtime manifest contains a non-object file row")
        path_value = row.get("path")
        if not isinstance(path_value, str) or not path_value or Path(path_value).is_absolute():
            raise ToolRuntimeError(f"tool runtime file path is not relative: {path_value!r}")
        path = root / Path(path_value)
        if ".." in Path(path_value).parts:
            raise ToolRuntimeError(f"tool runtime file path escapes root: {path_value}")
        if path_value in indexed:
            raise ToolRuntimeError(f"duplicate tool runtime file row: {path_value}")
        output_sha = row.get("output_sha256")
        if not isinstance(output_sha, str) or not _SHA256_RE.fullmatch(output_sha):
            raise ToolRuntimeError(f"invalid output hash for tool runtime file: {path_value}")
        _regular_file(path, "manifest-bound tool runtime file")
        if _sha256_file(path) != output_sha:
            raise ToolRuntimeError(f"tool runtime file hash mismatch: {path_value}")
        mode = row.get("mode")
        if not isinstance(mode, int) or stat.S_IMODE(path.stat().st_mode) != mode:
            raise ToolRuntimeError(f"tool runtime file mode mismatch: {path_value}")
        indexed[path_value] = row
    actual = _actual_regular_files(root)
    actual.discard(TOOL_RUNTIME_MANIFEST_NAME)
    if actual != set(indexed):
        raise ToolRuntimeError(
            f"tool runtime file inventory mismatch; missing={sorted(set(indexed) - actual)}, "
            f"unexpected={sorted(actual - set(indexed))}"
        )
    if manifest.get("file_count") != len(indexed):
        raise ToolRuntimeError("tool runtime file_count does not match file rows")
    return indexed


def validate_tool_runtime_bundle(
    manifest_path: Path,
    expected_sha256: str,
    *,
    expected_config_path: Path,
    expected_swe_agent_revision: str,
) -> dict[str, Any]:
    """Fail closed if a copied tool overlay is incomplete or drifted.

    The validator intentionally operates from the saved manifest directory;
    no original checkout is needed.  This lets the production runner validate
    the exact bundle copied into a case's execution inputs before launching
    SWE-agent.
    """

    manifest_path = manifest_path.expanduser().resolve()
    _regular_file(manifest_path, "tool runtime manifest")
    if not _SHA256_RE.fullmatch(expected_sha256):
        raise ToolRuntimeError("expected tool runtime manifest SHA-256 is not canonical")
    actual_manifest_sha = _sha256_file(manifest_path)
    if actual_manifest_sha != expected_sha256:
        raise ToolRuntimeError("tool runtime manifest SHA-256 mismatch")
    manifest = _read_json(manifest_path, "tool runtime manifest")
    if manifest.get("schema_version") != TOOL_RUNTIME_SCHEMA:
        raise ToolRuntimeError("unsupported tool runtime manifest schema")
    if manifest.get("upstream_repository") != "SWE-agent":
        raise ToolRuntimeError("tool runtime manifest upstream repository is not SWE-agent")
    if manifest.get("upstream_revision") != expected_swe_agent_revision:
        raise ToolRuntimeError("tool runtime manifest upstream revision mismatch")
    if manifest.get("bundles") != list(TOOL_BUNDLE_NAMES):
        raise ToolRuntimeError("tool runtime manifest bundle set is not the reviewed set")
    runtime = manifest.get("runtime")
    if not isinstance(runtime, dict) or runtime.get("no_task_path_change") is not True:
        raise ToolRuntimeError("tool runtime manifest does not prove task PATH preservation")
    remote_venv = runtime.get("remote_venv")
    if (
        not isinstance(remote_venv, str)
        or runtime.get("python_entrypoint_shebang") != f"#!{remote_venv}/bin/python"
    ):
        raise ToolRuntimeError("tool runtime Python entrypoint binding is inconsistent")
    root = manifest_path.parent
    rows = _check_manifest_rows(manifest, root)
    archive_root = manifest.get("source_archive_root")
    if (
        not isinstance(archive_root, str)
        or Path(archive_root).is_absolute()
        or ".." in Path(archive_root).parts
    ):
        raise ToolRuntimeError("tool runtime source archive root is unsafe")
    source_config_paths = manifest.get("source_config_paths")
    if not isinstance(source_config_paths, list) or not source_config_paths:
        raise ToolRuntimeError("tool runtime source config archive list is missing")
    checked_config_paths: set[str] = set()
    for relative in source_config_paths:
        path = Path(relative) if isinstance(relative, str) else None
        if (
            path is None
            or not relative
            or path.is_absolute()
            or ".." in path.parts
            or path.as_posix() != relative
            or relative in checked_config_paths
        ):
            raise ToolRuntimeError(f"tool runtime source config path is unsafe: {relative!r}")
        checked_config_paths.add(relative)
    for row in rows.values():
        source_path = row.get("source_path")
        source_sha = row.get("source_sha256")
        source_blob = row.get("source_git_blob_sha1")
        is_archived_source = isinstance(source_path, str) and (
            source_path.startswith("tools/") or source_path in checked_config_paths
        )
        if not (
            isinstance(source_path, str)
            and is_archived_source
            and isinstance(source_sha, str)
            and isinstance(source_blob, str)
        ):
            continue
        archive_path = f"{archive_root}/{source_path}"
        archive_row = rows.get(archive_path)
        if archive_row is None:
            raise ToolRuntimeError(f"source archive is missing {source_path}")
        if (
            archive_row.get("source_sha256") != source_sha
            or archive_row.get("source_git_blob_sha1") != source_blob
        ):
            raise ToolRuntimeError(f"source archive binding mismatch for {source_path}")
    for relative in checked_config_paths:
        archive_path = f"{archive_root}/{relative}"
        archive_row = rows.get(archive_path)
        if (
            archive_row is None
            or archive_row.get("source_path") != relative
            or not isinstance(archive_row.get("source_sha256"), str)
            or not isinstance(archive_row.get("source_git_blob_sha1"), str)
        ):
            raise ToolRuntimeError(f"source config archive is missing {relative}")

    metadata_relative = manifest.get("metadata_config_path")
    if (
        not isinstance(metadata_relative, str)
        or Path(metadata_relative).is_absolute()
        or ".." in Path(metadata_relative).parts
    ):
        raise ToolRuntimeError("tool runtime metadata config path is unsafe")
    metadata_path = root / metadata_relative
    metadata = _read_json(metadata_path, "tool runtime metadata config")
    if metadata.get("schema_version") != TOOL_RUNTIME_CONFIG_SCHEMA:
        raise ToolRuntimeError("unsupported tool runtime metadata config schema")
    if metadata.get("upstream_revision") != expected_swe_agent_revision:
        raise ToolRuntimeError("tool runtime metadata config upstream revision mismatch")
    if metadata.get("manifest_path") != TOOL_RUNTIME_MANIFEST_NAME:
        raise ToolRuntimeError("tool runtime metadata config does not bind the manifest basename")
    metadata_row = rows.get(metadata_relative)
    if metadata_row is None or _sha256_file(metadata_path) != metadata_row["output_sha256"]:
        raise ToolRuntimeError("tool runtime metadata config is not bound by the manifest")
    config = metadata
    bundles = config.get("bundles")
    if (
        not isinstance(bundles, list)
        or [row.get("name") for row in bundles] != list(TOOL_BUNDLE_NAMES)
    ):
        raise ToolRuntimeError("tool runtime config bundle order/set is invalid")
    for row in bundles:
        if not isinstance(row, dict):
            raise ToolRuntimeError("tool runtime config contains a non-object bundle")
        relative = row.get("path")
        if (
            not isinstance(relative, str)
            or Path(relative).is_absolute()
            or ".." in Path(relative).parts
        ):
            raise ToolRuntimeError("tool runtime config bundle path is unsafe")
        bundle_path = root / relative
        _directory(bundle_path, "configured tool bundle")
        if row.get("remote_path") != f"{runtime.get('remote_tools_root')}/{row.get('name')}":
            raise ToolRuntimeError("tool runtime config remote bundle path is inconsistent")
    offline = config.get("offline_dependencies")
    if not isinstance(offline, dict) or offline.get("bundle") != "edit_anthropic":
        raise ToolRuntimeError("tool runtime offline dependency binding is missing")
    requirements_relative = offline.get("requirements_path")
    wheelhouse_relative = offline.get("wheelhouse_path")
    if (
        not isinstance(requirements_relative, str)
        or not isinstance(wheelhouse_relative, str)
        or Path(requirements_relative).is_absolute()
        or Path(wheelhouse_relative).is_absolute()
        or ".." in Path(requirements_relative).parts
        or ".." in Path(wheelhouse_relative).parts
    ):
        raise ToolRuntimeError("tool runtime offline dependency paths are unsafe")
    requirements_path = root / requirements_relative
    wheelhouse_path = root / wheelhouse_relative
    _regular_file(requirements_path, "tool runtime requirements lock")
    _directory(wheelhouse_path, "tool runtime wheelhouse")
    if requirements_relative not in rows:
        # The wheelhouse itself is represented by its individual file rows;
        # the directory name need not have a synthetic hash row.
        raise ToolRuntimeError("tool runtime offline dependency paths are not manifest-bound")
    install_path = root / "bundles" / "edit_anthropic" / "install.sh"
    _regular_file(install_path, "tool runtime installer")
    install_text = install_path.read_text(encoding="utf-8")
    bootstrap_python = runtime.get("bootstrap_python")
    if not isinstance(bootstrap_python, str) or not bootstrap_python:
        raise ToolRuntimeError("tool runtime bootstrap interpreter is missing")
    for required in ("--no-index", "--require-hashes", "tool_venv", "requirements.lock"):
        if required not in install_text:
            raise ToolRuntimeError(
                f"tool runtime installer is missing fail-closed marker: {required}"
            )
    if bootstrap_python not in install_text:
        raise ToolRuntimeError(
            "tool runtime installer does not bind the manifest bootstrap interpreter"
        )
    if re.search(r"(?m)^\s*(?:pip|pip3)\s+install\b", install_text):
        raise ToolRuntimeError("tool runtime installer still invokes a bare pip")
    for bundle_name in TOOL_BUNDLE_NAMES:
        bin_root = root / "bundles" / bundle_name / "bin"
        if not bin_root.exists():
            continue
        for current, _directories, filenames in os.walk(bin_root, followlinks=False):
            for filename in filenames:
                path = Path(current) / filename
                _regular_file(path, "tool entrypoint")
                first_line = path.read_bytes().splitlines()[:1]
                if (
                    first_line
                    and b"python" in first_line[0]
                    and first_line[0] != f"#!{remote_venv}/bin/python".encode()
                ):
                    raise ToolRuntimeError(
                        f"tool entrypoint is not bound to the isolated interpreter: {path}"
                    )
    sweagent_config = _validate_sweagent_config(
        expected_config_path.expanduser().resolve(),
        root,
        expected_swe_agent_revision,
    )
    return {
        "schema_version": TOOL_RUNTIME_SCHEMA,
        "manifest_sha256": actual_manifest_sha,
        "config_sha256": sweagent_config["sha256"],
        "metadata_config_sha256": _sha256_file(metadata_path),
        "upstream_revision": expected_swe_agent_revision,
        "file_count": len(rows),
        "bundles": list(TOOL_BUNDLE_NAMES),
        "root": str(root),
    }


__all__ = [
    "DEFAULT_BOOTSTRAP_PYTHON",
    "DEFAULT_REMOTE_TOOLS_ROOT",
    "DEFAULT_REMOTE_VENV",
    "DEFAULT_UPSTREAM_CONFIG_PATHS",
    "TOOL_BUNDLE_NAMES",
    "TOOL_RUNTIME_CONFIG_SCHEMA",
    "TOOL_RUNTIME_MANIFEST_NAME",
    "TOOL_RUNTIME_SCHEMA",
    "ToolRuntimeBuild",
    "ToolRuntimeError",
    "ToolRuntimeSpec",
    "WheelPin",
    "build_tool_runtime",
    "materialize_sweagent_config",
    "validate_tool_runtime_bundle",
]
