#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"; MANIFEST="${LAMBDA_MANIFEST:-$ROOT/cloud/lambda/instance_manifest.env}"; WORK_ROOT="${WORK_ROOT:-$ROOT/../agentic-work}"; MODEL="${VLLM_MODEL:-}"; REVISION="${VLLM_MODEL_REVISION:-}"; PORT="${VLLM_PORT:-8000}"; TASK_ID="${TASK_ID:-vllm-server}"; EXPERIMENT_ID="${EXPERIMENT_ID:-}"; LOG_DIR="$WORK_ROOT/logs/vllm"; SESSION="vllm-agentic"; LOCK_DIR="${VLLM_GPU_LOCK_DIR:-$WORK_ROOT/locks/gpu-0.lock}"; DRY=0
usage(){ echo 'Usage: lambda_start_vllm.sh [--manifest FILE] [--config YAML] [--work-root DIR] [--dry-run]'; }
prev=''; cfg=''; for a in "$@"; do case "$a" in --dry-run) DRY=1;; --manifest) :;; --manifest=*) MANIFEST="${a#*=}";; --config) :;; --config=*) cfg="${a#*=}";; --work-root) :;; --work-root=*) WORK_ROOT="${a#*=}";; -h|--help) usage; exit 0;; *) if [[ "$prev" == --manifest ]]; then MANIFEST="$a"; elif [[ "$prev" == --config ]]; then cfg="$a"; elif [[ "$prev" == --work-root ]]; then WORK_ROOT="$a"; else echo "unknown argument: $a" >&2; exit 2; fi;; esac; prev="$a"; done
if [[ -f "$MANIFEST" ]]; then while IFS= read -r line || [[ -n "$line" ]]; do line="${line%%#*}"; key="${line%%=*}"; val="${line#*=}"; case "$key" in VLLM_MODEL) MODEL="$val";; VLLM_MODEL_REVISION) REVISION="$val";; VLLM_PORT) PORT="$val";; VLLM_TMUX_SESSION) SESSION="$val";; TASK_ID) TASK_ID="$val";; EXPERIMENT_ID) EXPERIMENT_ID="$val";; esac; done <"$MANIFEST"; fi
if [[ -n "$cfg" && -f "$cfg" ]]; then while IFS=: read -r k v; do k="${k// /}"; v="${v# }"; case "$k" in model) MODEL="$v";; model_revision) REVISION="$v";; port|vllm_port) PORT="$v";; esac; done < <(sed -n '/^[[:space:]]*[A-Za-z_][A-Za-z_0-9]*[[:space:]]*:/p' "$cfg"); fi
if ((DRY)); then echo "DRY-RUN: atomically acquire $LOCK_DIR, then vllm serve $MODEL --revision $REVISION --host 127.0.0.1 --port $PORT --dtype bfloat16 --max-model-len 8192 --gpu-memory-utilization 0.90 --tensor-parallel-size 1 --enable-auto-tool-choice on CUDA device 0 under tmux."; exit 0; fi
[[ -n "$MODEL" && -n "$REVISION" ]] || { echo 'pinned model and revision are required' >&2; exit 1; }; command -v vllm >/dev/null || { echo 'vllm is unavailable' >&2; exit 1; }; command -v tmux >/dev/null || { echo 'tmux is required' >&2; exit 1; }; mkdir -p -- "$LOG_DIR" "$WORK_ROOT/artifacts/manifests" "$(dirname -- "$LOCK_DIR")"; manifest="$WORK_ROOT/artifacts/manifests/vllm_server.json"; [[ ! -f "$manifest" ]] || { pid="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("pid", ""))' "$manifest" 2>/dev/null || true)"; [[ -z "$pid" || ! -d "/proc/$pid" ]] || { echo "server already running with pid $pid" >&2; exit 1; }; }; tmux has-session -t "$SESSION" 2>/dev/null && { echo "tmux session already exists: $SESSION" >&2; exit 1; };
port_in_use() { if command -v ss >/dev/null 2>&1; then ss -ltn "sport = :$PORT" 2>/dev/null | awk 'NR > 1 {found=1} END {exit !found}'; elif command -v lsof >/dev/null 2>&1; then lsof -nP -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; else return 1; fi; }
gpu_in_use() { command -v nvidia-smi >/dev/null 2>&1 && [[ -n "$(nvidia-smi --query-compute-apps=pid --format=csv,noheader 2>/dev/null | sed '/^[[:space:]]*$/d')" ]]; }
if ! mkdir -- "$LOCK_DIR" 2>/dev/null; then
  owner_pid="$(cat "$LOCK_DIR/pid" 2>/dev/null || true)"
  if [[ "$owner_pid" =~ ^[0-9]+$ && -d "/proc/$owner_pid" ]]; then echo "GPU 0 is leased by pid $owner_pid ($LOCK_DIR)" >&2; exit 1; fi
  if port_in_use || gpu_in_use; then echo "stale-looking GPU lease has an active port or CUDA process; inspect before clearing: $LOCK_DIR" >&2; exit 1; fi
  echo "removing stale GPU 0 lease: $LOCK_DIR" >&2
  rm -f -- "$LOCK_DIR/pid" "$LOCK_DIR/owner.json"
  rmdir -- "$LOCK_DIR" 2>/dev/null || { echo "unable to clear stale GPU lease: $LOCK_DIR" >&2; exit 1; }
  mkdir -- "$LOCK_DIR"
fi
lock_acquired=1
cleanup_lock() { if ((lock_acquired)); then rm -f -- "$LOCK_DIR/pid" "$LOCK_DIR/owner.json"; rmdir -- "$LOCK_DIR" 2>/dev/null || true; fi; }
trap cleanup_lock EXIT
printf '%s\n' "$$" >"$LOCK_DIR/pid"
cmd=(vllm serve "$MODEL" --revision "$REVISION" --host 127.0.0.1 --port "$PORT" --dtype bfloat16 --max-model-len 8192 --gpu-memory-utilization 0.90 --tensor-parallel-size 1 --enable-auto-tool-choice); printf -v q ' %q' "${cmd[@]}"; config_hash="$(python3 - "$MODEL" "$REVISION" "$PORT" <<'PY'
import hashlib, sys
print(hashlib.sha256("\0".join(sys.argv[1:]).encode()).hexdigest())
PY
)"; tmux new-session -d -s "$SESSION" "CUDA_VISIBLE_DEVICES=0 ${q# } >>$(printf %q "$LOG_DIR/server.log") 2>&1"; sleep 1; pid="$(tmux list-panes -t "$SESSION" -F '#{pane_pid}' | head -n1)"; [[ "$pid" =~ ^[0-9]+$ ]] || { echo 'could not determine vLLM pane PID' >&2; exit 1; }; printf '%s\n' "$pid" >"$LOCK_DIR/pid"; python3 -c 'import json,pathlib,sys,time; o,p,port,m,r,s,l,lock,t,e,h,c=sys.argv[1:]; pathlib.Path(o).write_text(json.dumps({"schema_version":"vllm-server.v1","pid":int(p),"host":"127.0.0.1","port":int(port),"model":m,"model_revision":r,"cuda_visible_devices":"0","tmux_session":s,"log_path":l,"gpu_lock":lock,"task_id":t,"experiment_id":e,"hostname":h,"config_hash":c,"started_at_epoch":time.time()},indent=2)+"\n")' "$manifest" "$pid" "$PORT" "$MODEL" "$REVISION" "$SESSION" "$LOG_DIR/server.log" "$LOCK_DIR" "$TASK_ID" "$EXPERIMENT_ID" "$(hostname)" "$config_hash"; python3 -c 'import json,pathlib,sys,time; o,p,m,r,s,t,e,h,port,c=sys.argv[1:]; pathlib.Path(o).write_text(json.dumps({"schema_version":"gpu-lease.v1","pid":int(p),"gpu":"0","model":m,"model_revision":r,"tmux_session":s,"task_id":t,"experiment_id":e,"hostname":h,"vllm_port":int(port),"config_hash":c,"acquired_at_utc":time.strftime("%Y-%m-%dT%H:%M:%SZ",time.gmtime())},indent=2)+"\n")' "$LOCK_DIR/owner.json" "$pid" "$MODEL" "$REVISION" "$SESSION" "$TASK_ID" "$EXPERIMENT_ID" "$(hostname)" "$PORT" "$config_hash"; lock_acquired=0; echo "vLLM started: tmux=$SESSION manifest=$manifest gpu_lock=$LOCK_DIR"
