#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"; MANIFEST="${LAMBDA_MANIFEST:-$ROOT/cloud/lambda/instance_manifest.env}"; OUT="${PREFLIGHT_OUTPUT:-$ROOT/artifacts/manifests/lambda_preflight.json}"; DRY=0; PORT=8000; MIN_FREE_GB=150
usage(){ echo 'Usage: lambda_preflight.sh [--manifest FILE] [--output FILE] [--dry-run]'; }
prev=''; for a in "$@"; do case "$a" in --dry-run) DRY=1;; --manifest) :;; --manifest=*) MANIFEST="${a#*=}";; --output) :;; --output=*) OUT="${a#*=}";; -h|--help) usage; exit 0;; *) if [[ "$prev" == --manifest ]]; then MANIFEST="$a"; elif [[ "$prev" == --output ]]; then OUT="$a"; else echo "unknown argument: $a" >&2; exit 2; fi;; esac; prev="$a"; done
if [[ -f "$MANIFEST" ]]; then while IFS= read -r line || [[ -n "$line" ]]; do line="${line%%#*}"; key="${line%%=*}"; val="${line#*=}"; case "$key" in VLLM_PORT) PORT="$val";; MIN_FREE_GB) MIN_FREE_GB="$val";; WORK_ROOT) WORK_ROOT="$val";; esac; done <"$MANIFEST"; fi
if ((DRY)); then echo 'DRY-RUN: inspect GPU, driver, Docker, disk, network, ports, clock, and processes; write nothing.'; exit 0; fi
mkdir -p -- "$(dirname -- "$OUT")"; declare -a fail=() warn=()
gpu='unavailable'; mem=0; count=0; cap='unknown'; driver='unknown'; procs='unknown'
if command -v nvidia-smi >/dev/null 2>&1; then info="$(nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader 2>/dev/null || true)"; gpu="$(awk -F, 'NR==1{gsub(/^ +| +$/, "",$1);print $1}' <<<"$info")"; count="$(nvidia-smi -L 2>/dev/null | wc -l | tr -d ' ')"; mem="$(awk -F, 'NR==1{gsub(/[^0-9.]/,"",$2);printf "%.0f",$2*1.024}' <<<"$info")"; driver="$(awk -F, 'NR==1{gsub(/^ +| +$/, "",$3);print $3}' <<<"$info")"; cap="$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -n1 | tr -d ' ' || true)"; procs="$(nvidia-smi --query-compute-apps=pid,process_name --format=csv,noheader 2>/dev/null || true)"; [[ "$count" == 1 ]] || fail+=("expected exactly one GPU; found $count"); [[ "$gpu" == *H100* ]] || fail+=("GPU is not H100-class: $gpu"); ((mem >= 78000)) || fail+=("GPU has less than 80 GiB: ${mem} MiB"); [[ -n "$cap" ]] || fail+=("compute capability unavailable"); [[ -z "$procs" ]] || fail+=("GPU process already running: $procs"); else fail+=("nvidia-smi unavailable"); fi
docker_state='unavailable'; if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then docker_state='available'; docker run --pull=never --rm hello-world >/dev/null 2>&1 || warn+=('hello-world not cached; bootstrap must pull it'); else fail+=('Docker daemon/user access unavailable'); fi
free_kib="$(df -Pk "${WORK_ROOT:-$ROOT}" 2>/dev/null | awk 'NR==2{print $4}' || echo 0)"; ((free_kib >= MIN_FREE_GB*1024*1024)) || fail+=("less than ${MIN_FREE_GB} GiB free")
missing=(); for t in git curl jq rsync tmux tar zstd; do command -v "$t" >/dev/null 2>&1 || missing+=("$t"); done; ((${#missing[@]})) && warn+=("missing utilities: ${missing[*]}")
in_use=0; if command -v ss >/dev/null 2>&1 && ss -ltn | awk -v p=":$PORT" '$4~p"$"{x=1}END{exit !x}'; then in_use=1; fi; ((in_use==0)) || fail+=("port $PORT is occupied")
net=0; if command -v curl >/dev/null 2>&1; then net=1; for e in https://github.com https://huggingface.co https://pypi.org https://registry-1.docker.io; do curl --connect-timeout 5 --max-time 10 -fsSI "$e" >/dev/null 2>&1 || net=0; done; else fail+=('curl unavailable'); fi; ((net)) || fail+=('required outbound endpoint unreachable')
status=PASS; ((${#fail[@]})) && status=BLOCKED; printf '{"schema_version":"lambda-preflight.v1","status":"%s","host":"%s","gpu":"%s","gpu_memory_mib":%s,"gpu_count":%s,"compute_capability":"%s","driver":"%s","docker":"%s","network_checked":%s,"port":%s,"blocking_failures":%s,"warnings":%s}\n' "$status" "$(hostname)" "$gpu" "${mem:-0}" "${count:-0}" "$cap" "$driver" "$docker_state" "$net" "$PORT" "$(printf '%s\n' "${fail[@]}" | python3 -c 'import json,sys; print(json.dumps([x.rstrip() for x in sys.stdin]))')" "$(printf '%s\n' "${warn[@]}" | python3 -c 'import json,sys; print(json.dumps([x.rstrip() for x in sys.stdin]))')" >"$OUT"
echo "lambda preflight: $status (report $OUT)"; for x in "${fail[@]}"; do echo "blocking: $x" >&2; done; for x in "${warn[@]}"; do echo "warning: $x" >&2; done; [[ "$status" == PASS ]]
