#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"; MANIFEST="${LAMBDA_MANIFEST:-$ROOT/cloud/lambda/instance_manifest.env}"; WORK_ROOT="${WORK_ROOT:-$ROOT/../agentic-work}"; CACHE_ROOT="$WORK_ROOT/cache"; DRY=0
usage(){ echo 'Usage: lambda_download_assets.sh [--manifest FILE] [--work-root DIR] [--dry-run]'; }
prev=''; for a in "$@"; do case "$a" in --dry-run) DRY=1;; --manifest) :;; --manifest=*) MANIFEST="${a#*=}";; --work-root) :;; --work-root=*) WORK_ROOT="${a#*=}";; -h|--help) usage; exit 0;; *) if [[ "$prev" == --manifest ]]; then MANIFEST="$a"; elif [[ "$prev" == --work-root ]]; then WORK_ROOT="$a"; else echo "unknown argument: $a" >&2; exit 2; fi;; esac; prev="$a"; done
MODEL="${VLLM_MODEL:-}"; REVISION="${VLLM_MODEL_REVISION:-}"; if [[ -f "$MANIFEST" ]]; then while IFS= read -r line || [[ -n "$line" ]]; do line="${line%%#*}"; key="${line%%=*}"; val="${line#*=}"; case "$key" in VLLM_MODEL) MODEL="$val";; VLLM_MODEL_REVISION) REVISION="$val";; CACHE_ROOT) CACHE_ROOT="$val";; esac; done <"$MANIFEST"; fi
if [[ -z "$MODEL" || -z "$REVISION" ]]; then ((DRY)) && { echo 'DRY-RUN: configure immutable VLLM_MODEL and VLLM_MODEL_REVISION before downloading.'; exit 0; }; echo 'VLLM_MODEL and VLLM_MODEL_REVISION are required; floating revisions are forbidden.' >&2; exit 1; fi
if ((DRY)); then echo "DRY-RUN: download $MODEL@$REVISION to $CACHE_ROOT/huggingface using resumable hf cache."; exit 0; fi
mkdir -p -- "$CACHE_ROOT/huggingface" "$WORK_ROOT/logs" "$WORK_ROOT/artifacts/manifests"; command -v hf >/dev/null 2>&1 || { echo 'hf CLI missing; install pinned huggingface_hub first' >&2; exit 1; }; export HF_HOME="$CACHE_ROOT/huggingface" HUGGINGFACE_HUB_CACHE="$CACHE_ROOT/huggingface"; start="$(date +%s)"; hf download "$MODEL" --revision "$REVISION" --cache-dir "$CACHE_ROOT/huggingface" --include '*.json' '*.safetensors' '*.model' '*.txt' '*.py' '*.jinja' --exclude '*optimizer*' '*checkpoint*' 2>&1 | tee "$WORK_ROOT/logs/model_download.log"; end="$(date +%s)"; snapshot="$(find "$CACHE_ROOT/huggingface" -type d -path "*/snapshots/$REVISION" -print -quit 2>/dev/null || true)"; [[ -d "$snapshot" ]] || { echo 'expected revision snapshot not found' >&2; exit 1; }
python3 -c 'import json,pathlib,sys; o,m,r,s,a,b=sys.argv[1:]; fs=[{"path":str(p.relative_to(s)),"bytes":p.stat().st_size} for p in pathlib.Path(s).rglob("*") if p.is_file()]; pathlib.Path(o).write_text(json.dumps({"schema_version":"model-download.v1","model":m,"revision":r,"duration_seconds":int(b)-int(a),"total_bytes":sum(x["bytes"] for x in fs),"files":fs},indent=2)+"\n")' "$WORK_ROOT/artifacts/manifests/model_download.json" "$MODEL" "$REVISION" "$snapshot" "$start" "$end"; echo "Pinned model verified: $MODEL@$REVISION"
