#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"; MANIFEST="${LAMBDA_MANIFEST:-$ROOT/cloud/lambda/instance_manifest.env}"; WORK_ROOT="${WORK_ROOT:-$ROOT/../agentic-work}"; MODEL="${VLLM_MODEL:-}"; REVISION="${VLLM_MODEL_REVISION:-}"; PORT="${VLLM_PORT:-8000}"; LOG_DIR="$WORK_ROOT/logs/vllm"; SESSION="vllm-agentic"; DRY=0
usage(){ echo 'Usage: lambda_start_vllm.sh [--manifest FILE] [--config YAML] [--work-root DIR] [--dry-run]'; }
prev=''; cfg=''; for a in "$@"; do case "$a" in --dry-run) DRY=1;; --manifest) :;; --manifest=*) MANIFEST="${a#*=}";; --config) :;; --config=*) cfg="${a#*=}";; --work-root) :;; --work-root=*) WORK_ROOT="${a#*=}";; -h|--help) usage; exit 0;; *) if [[ "$prev" == --manifest ]]; then MANIFEST="$a"; elif [[ "$prev" == --config ]]; then cfg="$a"; elif [[ "$prev" == --work-root ]]; then WORK_ROOT="$a"; else echo "unknown argument: $a" >&2; exit 2; fi;; esac; prev="$a"; done
if [[ -f "$MANIFEST" ]]; then while IFS= read -r line || [[ -n "$line" ]]; do line="${line%%#*}"; key="${line%%=*}"; val="${line#*=}"; case "$key" in VLLM_MODEL) MODEL="$val";; VLLM_MODEL_REVISION) REVISION="$val";; VLLM_PORT) PORT="$val";; VLLM_TMUX_SESSION) SESSION="$val";; esac; done <"$MANIFEST"; fi
if [[ -n "$cfg" && -f "$cfg" ]]; then while IFS=: read -r k v; do k="${k// /}"; v="${v# }"; case "$k" in model) MODEL="$v";; model_revision) REVISION="$v";; port|vllm_port) PORT="$v";; esac; done < <(sed -n '/^[[:space:]]*[A-Za-z_][A-Za-z_0-9]*[[:space:]]*:/p' "$cfg"); fi
if ((DRY)); then echo "DRY-RUN: vllm serve $MODEL --revision $REVISION --host 127.0.0.1 --port $PORT --dtype bfloat16 --max-model-len 8192 --gpu-memory-utilization 0.90 --tensor-parallel-size 1 --enable-auto-tool-choice on CUDA device 0 under tmux."; exit 0; fi
[[ -n "$MODEL" && -n "$REVISION" ]] || { echo 'pinned model and revision are required' >&2; exit 1; }; command -v vllm >/dev/null || { echo 'vllm is unavailable' >&2; exit 1; }; command -v tmux >/dev/null || { echo 'tmux is required' >&2; exit 1; }; mkdir -p -- "$LOG_DIR" "$WORK_ROOT/artifacts/manifests"; manifest="$WORK_ROOT/artifacts/manifests/vllm_server.json"; [[ ! -f "$manifest" ]] || { pid="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("pid", ""))' "$manifest" 2>/dev/null || true)"; [[ -z "$pid" || ! -d "/proc/$pid" ]] || { echo "server already running with pid $pid" >&2; exit 1; }; }; tmux has-session -t "$SESSION" 2>/dev/null && { echo "tmux session already exists: $SESSION" >&2; exit 1; }; cmd=(vllm serve "$MODEL" --revision "$REVISION" --host 127.0.0.1 --port "$PORT" --dtype bfloat16 --max-model-len 8192 --gpu-memory-utilization 0.90 --tensor-parallel-size 1 --enable-auto-tool-choice); printf -v q ' %q' "${cmd[@]}"; tmux new-session -d -s "$SESSION" "CUDA_VISIBLE_DEVICES=0 ${q# } >>$(printf %q "$LOG_DIR/server.log") 2>&1"; sleep 1; pid="$(tmux list-panes -t "$SESSION" -F '#{pane_pid}' | head -n1)"; python3 -c 'import json,pathlib,sys,time; o,p,port,m,r,s,l=sys.argv[1:]; pathlib.Path(o).write_text(json.dumps({"schema_version":"vllm-server.v1","pid":int(p),"host":"127.0.0.1","port":int(port),"model":m,"model_revision":r,"cuda_visible_devices":"0","tmux_session":s,"log_path":l,"started_at_epoch":time.time()},indent=2)+"\n")' "$manifest" "$pid" "$PORT" "$MODEL" "$REVISION" "$SESSION" "$LOG_DIR/server.log"; echo "vLLM started: tmux=$SESSION manifest=$manifest"
